import React from 'react';
import {
  AbsoluteFill,
  Audio,
  Img,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from 'remotion';
import {ramp} from './anim';
import {Scene} from './components/Scene';
import {Closing} from './scenes/Closing';
import {Features} from './scenes/Features';
import {GridScene} from './scenes/GridScene';
import {Hook} from './scenes/Hook';
import {LogoReveal} from './scenes/LogoReveal';
import {OverlayDemo} from './scenes/OverlayDemo';
import {APP_ICON, dark, FONT, STAGE} from './theme';
import {SCENES} from './timing';

const P = dark;

/**
 * Square and vertical cuts letterbox the same 16:9 stage and fill the spare
 * room with the wordmark, rather than re-laying every scene out twice.
 */
const Band: React.FC<{height: number; place: 'top' | 'bottom'}> = ({
  height,
  place,
}) => {
  const frame = useCurrentFrame();
  const p = ramp(frame, 4, 16);
  // A 9:16 band is nearly three times the height of a 1:1 one — grow the
  // lockup with it so the wordmark doesn't float in an empty field.
  const k = Math.max(0.9, Math.min(1.85, height / 250));

  return (
    <div
      style={{
        height,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontFamily: FONT,
        opacity: p,
      }}
    >
      {place === 'top' ? (
        <div style={{display: 'flex', alignItems: 'center', gap: 16 * k}}>
          <Img
            src={staticFile(APP_ICON)}
            style={{width: 54 * k, height: 54 * k}}
          />
          <span
            style={{
              fontSize: 54 * k,
              fontWeight: 700,
              letterSpacing: '-0.03em',
              color: P.textPrimary,
            }}
          >
            Puchne
          </span>
        </div>
      ) : (
        <div style={{textAlign: 'center'}}>
          <div
            style={{fontSize: 34 * k, fontWeight: 600, color: P.textSecondary}}
          >
            One prompt. Every AI.{' '}
            <span style={{color: P.accent}}>At once.</span>
          </div>
          <div
            style={{marginTop: 12 * k, fontSize: 22 * k, color: P.textMuted}}
          >
            github.com/arshit09/puchne
          </div>
        </div>
      )}
    </div>
  );
};

export const LaunchPromo: React.FC = () => {
  const {width, height} = useVideoConfig();

  // Fill the width, letterbox the height.
  const scale = width / STAGE.width;
  const stageHeight = STAGE.height * scale;
  const band = (height - stageHeight) / 2;
  const showBands = band > 110;

  return (
    <AbsoluteFill style={{background: P.bgPrimary}}>
      {showBands ? (
        <AbsoluteFill
          style={{display: 'flex', flexDirection: 'column'}}
        >
          <Band height={band} place="top" />
          <div style={{flex: 1}} />
          <Band height={band} place="bottom" />
        </AbsoluteFill>
      ) : null}

      <AbsoluteFill style={{alignItems: 'center', justifyContent: 'center'}}>
        <div
          style={{
            position: 'relative',
            width: STAGE.width,
            height: STAGE.height,
            transform: `scale(${scale})`,
            overflow: 'hidden',
            background: P.bgPrimary,
            flexShrink: 0,
          }}
        >
          <Scene name="1 · The old way" window={SCENES.hook}>
            <Hook />
          </Scene>
          <Scene name="2 · Puchne" window={SCENES.logo}>
            <LogoReveal />
          </Scene>
          <Scene name="3 · Ask once" window={SCENES.overlay}>
            <OverlayDemo />
          </Scene>
          <Scene name="4 · Compare" window={SCENES.grid}>
            <GridScene />
          </Scene>
          <Scene name="5 · Features" window={SCENES.features}>
            <Features />
          </Scene>
          <Scene name="6 · Install" window={SCENES.cta}>
            <Closing />
          </Scene>
        </div>
      </AbsoluteFill>

      {/* Original score, generated by tools/make-music.mjs from the same scene
          table this file lays out — chord changes land on the cuts. It carries
          its own fades, so no volume ramp is needed here. */}
      <Audio src={staticFile('music.mp3')} volume={0.9} />
    </AbsoluteFill>
  );
};
